yml file fixed

diff --git a/.github/workflows/terraform.yaml b/.github/workflows/terraform.yaml
--- a/.github/workflows/terraform.yaml
+++ b/.github/workflows/terraform.yaml
@@ -53,4 +53,6 @@ jobs:
           
         - name: Terraofrm plan status
           if: steps.plan.outcome == 'failure'
-          run: exit 1
+          run: 
+              echo "Terraform plan failed"
+              exit 1
